name: Dumper

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'Firmware Link'
        required: true

env:
  LINK: ${{ github.event.inputs.link }}
  TZ: Asia/Kolkata

jobs:
  Firmware-Dump:
      runs-on: ubuntu-22.04

      steps:

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main

        
      - name: SettingUp SSH Keys
        run: |
             mkdir -p ~/.ssh
             ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
             echo "${{ secrets.SSHKEY_PRIVATE }}" > ~/.ssh/id_rsa
             echo "${{ secrets.SSHKEY_PUBLIC }}" > ~/.ssh/id_rsa.pub
             chmod 600 ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa.pub
             ssh-agent -s
             eval "$(ssh-agent -s)"
             ssh-add ~/.ssh/id_rsa
        
      - name: Cloning Dumper
        run: |
             git config --global user.email "kousickdey3@gmail.com" && git config --global user.name "Koushik Dey"
             git clone https://github.com/Koushikdey2003/DumprX.git --depth=1

      - name: Installing Requirements
        run: |
             cd DumprX
             bash setup.sh

      - name: Firmware is Dumping
        run: |
             cd DumprX
             export PUSH_TO_GITLAB=true
             echo "koushiks-dumps2" > .gitlab_group
             echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token
             echo "${{ secrets.TGCHAT }}" > .tg_chat
             echo "${{ secrets.TGTOKEN }}" > .tg_token
             bash dumper.sh $LINK


